// Sample data for development - this would normally be seeded into the database
export const sampleProducts = [
  {
    _id: "sample1",
    name: "Margherita Pizza",
    description: "Fresh tomatoes, mozzarella, basil",
    price: 3.14, // Pi coins
    category: "Pizza",
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400",
    available: true,
    isAvailable: true,
    isPopular: true,
    storeId: "store1",
    ingredients: ["tomatoes", "mozzarella", "basil"],
  },
  {
    _id: "sample2", 
    name: "Pepperoni Pizza",
    description: "Classic pepperoni with cheese",
    price: 4.25,
    category: "Pizza",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400",
    available: true,
    isAvailable: true,
    isPopular: true,
    storeId: "store1",
    ingredients: ["pepperoni", "cheese"],
  },
  {
    _id: "sample3",
    name: "Caesar Salad",
    description: "Crisp romaine lettuce with Caesar dressing",
    price: 2.89,
    category: "Salads",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    available: true,
    isAvailable: true,
    isPopular: false,
    storeId: "store1",
    ingredients: ["romaine lettuce", "caesar dressing", "croutons"],
  },
  {
    _id: "sample4",
    name: "Chocolate Cake",
    description: "Rich chocolate cake with frosting",
    price: 1.99,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    available: true,
    isAvailable: true,
    isPopular: true,
    storeId: "store1",
    ingredients: ["chocolate", "flour", "sugar"],
  }
];

export const sampleStore = {
  _id: "store1",
  name: "OmniGo Pizza & More",
  description: "Delicious food delivered with Pi Network payments",
  categories: ["Pizza", "Salads", "Desserts"],
  storeType: "restaurant",
  priceRange: "$$",
  rating: 4.5,
  totalReviews: 127,
  country: "Global",
  region: "Worldwide",
  address: "123 Pi Street, Crypto City",
  hasDelivery: true,
  deliveryFee: 0.5,
  deliveryTime: "30-45 min",
  isOpen: true,
  openingHours: [
    { day: "Monday", isOpen: true, open: "09:00", close: "22:00" },
    { day: "Tuesday", isOpen: true, open: "09:00", close: "22:00" },
    { day: "Wednesday", isOpen: true, open: "09:00", close: "22:00" },
    { day: "Thursday", isOpen: true, open: "09:00", close: "22:00" },
    { day: "Friday", isOpen: true, open: "09:00", close: "23:00" },
    { day: "Saturday", isOpen: true, open: "10:00", close: "23:00" },
    { day: "Sunday", isOpen: true, open: "10:00", close: "21:00" }
  ],
  dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
  isTrending: true,
  hasOffer: true,
  offerText: "Free delivery on orders over 10 Pi!",
  ownerId: "owner1"
};